# AWS
aws:
  access-key-id: ${AWS_KINESIS_ACCESS_KEY_ID}
  secret-key: ${AWS_KINESIS_SECRET_ACCESS_KEY}

# Application
kinesis:
  stream:
    name: my-stream
    shard-id: shardId-000000000000

spring:
  profiles:
    active: aws-sdk
